Update Setup-Script-Arch with --noconfirm

diff --git a/Setup-Script-Arch b/Setup-Script-Arch
--- a/Setup-Script-Arch
+++ b/Setup-Script-Arch
@@ -23,7 +23,7 @@ for ((i = 0; i < ${#browsers[@]}; i++)); do
 done
 
 # Prompt user for selection
-read -p "Enter the number(s) corresponding to your choice(s), separated by spaces (for example, '1 3 4 6'): " selected_indices
+read -p "Enter the number(s) corresponding to your choice(s), separated by spaces (for example, "1 3 4 6"): " selected_indices
 
 # Convert selected_indices to an array of integers
 selected_indices=($selected_indices)
@@ -34,23 +34,23 @@ for index in ${selected_indices[@]}; do
     case "$browser" in
         "Firefox")   # Download Firefox
             echo "Downloading Firefox..."
-            sudo pacman -S -y firefox || echo "Failed to download Firefox"
+            sudo pacman -S --noconfirm firefox || echo "Failed to download Firefox"
             ;;
         "Chromium")   # Download Chromium
             echo "Downloading Chromium..."
-            sudo pacman -S -y chromium || echo "Failed to download Chromium"
+            sudo pacman -S --noconfirm chromium || echo "Failed to download Chromium"
             ;;
 		"Tor Browser")   # Download Tor Browser
             echo "Downloading Tor Browser..."
-            sudo pacman -S -y torbrowser-launcher || echo "Failed to download Tor Browser"
+            sudo pacman -S --noconfirm torbrowser-launcher || echo "Failed to download Tor Browser"
             ;;
 		"Vivaldi")   # Download Vivaldi
             echo "Downloading Vivaldi..."
-            sudo pacman -S -y vivaldi || echo "Failed to download Vivaldi"
+            sudo pacman -S --noconfirm vivaldi || echo "Failed to download Vivaldi"
             ;;
 		"Haskell")   # Download Haskell
 			echo "Downloading Haskell..."
-            sudo pacman -S -y haskell-open-browser || echo "Failed to download Haskell"
+            sudo pacman -S --noconfirm haskell-open-browser || echo "Failed to download Haskell"
             ;;
 		"Librewolf")   # Download Librewolf
 			echo "Downloading librewolf..."
@@ -78,17 +78,17 @@ echo "Finished!"
 # Updates packages
 
 echo "Updating packages - required"
-sudo pacman -Syu -y
+sudo pacman -Syu --noconfirm
 echo "All packages updated sucessfully"
 
 # Downloads required packages
 echo "downloading neccesary packages - required"
 # git
 echo "Downloading git"
-sudo pacman -S -y git
+sudo pacman -S --noconfirm git
 # yay
 echo "Downloading yay"
-sudo pacman -Syu --needed base-devel git
+sudo pacman -Syu --noconfirm --needed base-devel git
 git clone https://aur.archlinux.org/yay.git
 cd yay
 gpg --recv-key EBE41E90F6F12F6D
@@ -114,14 +114,14 @@ fi
 # making user directories
 if [[ ${master_answer,,} = "yes" ]]; then
     echo "Making user directories"
-    sudo pacman -S -y xdg-user-dirs
+    sudo pacman -S --noconfirm xdg-user-dirs
 	xdg-user-dirs-update
 elif [[ ${master_answer,,} = "no" ]]; then
     echo "Would you like to add user directories? (Y/N)"
     read download_answer
     if [[ ${download_answer,,} = "y" || $download_answer = "" ]]; then
       echo "Making user directories"
-      sudo pacman -S -y xdg-user-dirs
+      sudo pacman -S --noconfirm xdg-user-dirs
 	  xdg-user-dirs-update
     elif [[ ${download_answer,,} = "n" ]]; then
         echo "Skipping user directories"
@@ -155,14 +155,14 @@ fi
 # Downloading essential packages
 if [[ ${master_answer,,} = "yes" ]]; then
     echo "Downloading essential packages"
-    sudo pacman -S -y enchant mythes-en ttf-liberation hunspell-en_US ttf-bitstream-vera pkgstats adobe-source-sans-pro-fonts gst-plugins-good ttf-droid ttf-dejavu aspell-en icedtea-web gst-libav ttf-ubuntu-font-family ttf-anonymous-pro jre8-openjdk languagetool libmythes pip
+    sudo pacman -S --noconfirm enchant mythes-en ttf-liberation hunspell-en_US ttf-bitstream-vera pkgstats adobe-source-sans-pro-fonts gst-plugins-good ttf-droid ttf-dejavu aspell-en icedtea-web gst-libav ttf-ubuntu-font-family ttf-anonymous-pro jre8-openjdk languagetool libmythes pip
 	echo "Essential packages downloaded sucessfully"
 elif [[ ${master_answer,,} = "no" ]]; then
     echo "Would you like to download essential packages? (Y/N)"
     read download_answer
     if [[ ${download_answer,,} = "y" || $download_answer = "" ]]; then
     echo "Downloading essential packages"
-	sudo pacman -S enchant mythes-en ttf-liberation hunspell-en_US ttf-bitstream-vera pkgstats adobe-source-sans-pro-fonts gst-plugins-good ttf-droid ttf-dejavu aspell-en icedtea-web gst-libav ttf-ubuntu-font-family ttf-anonymous-pro jre8-openjdk languagetool libmythes pip
+	sudo pacman -S --noconfirm enchant mythes-en ttf-liberation hunspell-en_US ttf-bitstream-vera pkgstats adobe-source-sans-pro-fonts gst-plugins-good ttf-droid ttf-dejavu aspell-en icedtea-web gst-libav ttf-ubuntu-font-family ttf-anonymous-pro jre8-openjdk languagetool libmythes pip
     elif [[ ${download_answer,,} = "n" ]]; then
         echo "Skipping essential packages"
     else
@@ -180,11 +180,11 @@ get_cpu_brand() {
 # Install microcode based on brand
 case "$cpu_brand" in
     "GenuineIntel")
-        sudo pacman -S -y intel-ucode
+        sudo pacman -S --noconfirm intel-ucode
         echo "Downloading Intel Microcode..."
         ;;
     "AuthenticAMD")
-        sudo pacman -S -y amd-ucode
+        sudo pacman -S --noconfirm amd-ucode
         echo "Downloading AMD Microcode..."
         ;;
     *)
@@ -207,12 +207,12 @@ read -p "Enter the number corresponding to your CPU manufacturer: " selected_ind
 case "$selected_index" in
     1)
         brand="Intel"
-        sudo pacman -S -y intel-ucode
+        sudo pacman -S --noconfirm intel-ucode
         echo "Downloading Intel Microcode..."
         ;;
     2)
         brand="AMD"
-        sudo pacman -S -y amd-ucode
+        sudo pacman -S --noconfirm amd-ucode
         echo "Downloading AMD Microcode..."
         ;;
     3)
@@ -264,11 +264,11 @@ for package in "${packages[@]}"; do
         read download_answer
         if [[ ${download_answer,,} = "y" || $download_answer = "" ]]; then
             echo "Downloading $package..."
-            sudo pacman -S -y $package || echo "Failed to download $package"
+            sudo pacman -S --noconfirm $package || echo "Failed to download $package"
         fi
     elif [[ ${master_answer,,} = "yes" ]]; then
         echo "Downloading $package..."
-        sudo pacman -S -y $package || echo "Failed to download $package"
+        sudo pacman -S --noconfirm $package || echo "Failed to download $package"
     elif [[ ${download_answer,,} == "n" ]]; then
         echo "Skipping $package"
         continue
@@ -284,21 +284,21 @@ if [[ ${master_answer,,} = "no" ]]; then
     read download_package
     if [[ ${download_package,,} != "n" ]]; then
         echo "Installing Multimedia Codecs"
-        sudo pacman -S -y a52dec faac faad2 flac jasper lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 xvidcore gstreamer0.10-plugins || echo "Failed to install a codec"
+        sudo pacman -S --noconfirm a52dec faac faad2 flac jasper lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 xvidcore gstreamer0.10-plugins || echo "Failed to install a codec"
     fi
     echo "Multimedia Codecs successfully installed"
 fi
 
 if [[ ${master_answer,,} = "yes" ]]; then
     echo "Installing multimedia codecs"
-    sudo pacman -S -y a52dec faac faad2 flac jasper lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 xvidcore gstreamer0.10-plugins || echo "Failed to install a codec"
+    sudo pacman -S --noconfirm a52dec faac faad2 flac jasper lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 xvidcore gstreamer0.10-plugins || echo "Failed to install a codec"
     echo "Multimedia Codecs successfully installed"
 fi
 
 # Updates packages
 
 echo "Updating packages"
-sudo pacman -Syu -y
+sudo pacman -Syu --noconfirm
 
 # Reboots to set in changes
 if [[ ${master_answer,,} = "no" ]]; then
