Bug fixing

diff --git a/Setup-Scripts-Fedora b/Setup-Scripts-Fedora
--- a/Setup-Scripts-Fedora
+++ b/Setup-Scripts-Fedora
@@ -116,7 +116,7 @@ fi
 # Multimedia codecs
 echo "Installing multimedia codecs"
 sudo dnf install -y gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel || echo "Failed to install a codec"
-sudo dnf install -y lame\* --exclude=lame-devel || { echo "Failed to install a codec"; exit 1}
+sudo dnf install -y lame\* --exclude=lame-devel || { echo "Failed to install a codec"; exit 1; }
 echo "Upgrading multimedia codecs"
 sudo dnf group upgrade --with-optional Multimedia || echo "Failed to update codec(s)"
 echo "Multimedia Codecs successfully installed"
@@ -150,17 +150,17 @@ if [[ ${master_answer,,} = "no" ]]; then
 	read download_package
 	if [[ ${download_package,,} != "n" ]]; then
 		echo "disabling automatic reporting"
-		sudo systemctl stop abrt-journal-core.service || { echo "Failed to turn off automatic reporting"; exit 1 }
-		sudo systemctl disable abrt-journal-core.service || { echo "Failed to turn off automatic reporting"; exit 1 }
+		sudo systemctl stop abrt-journal-core.service || { echo "Failed to turn off automatic reporting"; exit 1; }
+		sudo systemctl disable abrt-journal-core.service || { echo "Failed to turn off automatic reporting"; exit 1; }
 
-		sudo systemctl stop abrt-oops.service || { echo "Failed to turn off automatic reporting"; exit 1 }
-		sudo systemctl disable abrt-oops.service || { echo "Failed to turn off automatic reporting"; exit 1 }
+		sudo systemctl stop abrt-oops.service || { echo "Failed to turn off automatic reporting"; exit 1; }
+		sudo systemctl disable abrt-oops.service || { echo "Failed to turn off automatic reporting"; exit 1; }
 
-		sudo systemctl stop abrt-xorg.service || { echo "Failed to turn off automatic reporting"; exit 1 }
-		sudo systemctl disable abrt-xorg.service || { echo "Failed to turn off automatic reporting"; exit 1 }
+		sudo systemctl stop abrt-xorg.service || { echo "Failed to turn off automatic reporting"; exit 1; }
+		sudo systemctl disable abrt-xorg.service || { echo "Failed to turn off automatic reporting"; exit 1; }
 
-		sudo systemctl stop abrtd.service || { echo "Failed to turn off automatic reporting"; exit 1 }
-		sudo systemctl disable abrtd.service || { echo "Failed to turn off automatic reporting"; exit 1 }
+		sudo systemctl stop abrtd.service || { echo "Failed to turn off automatic reporting"; exit 1; }
+		sudo systemctl disable abrtd.service || { echo "Failed to turn off automatic reporting"; exit 1; }
 	fi
 echo "Automatic reporting disabled"
 fi
